
[Setup]
Detail=1
Control=0
Haptic=1
joy_ipt_MenuNew=0
sys_midi=1
alsa_output_client=128
alsa_output_port=0
SoundFont=TimGM6mb.sf2

[Music]
Volume=74
CardType=8
MidiPort=330

[SoundFX]
Volume=85
CardType=5
Channels=4
BasePort=220
Irq=7
Dma=1

[Keyboard]
MoveUp=72
MoveDn=80
MoveLeft=75
MoveRight=77
Fire=30
FireSp=31
ChangeSp=32
MegaFire=54

[Mouse]
Fire=0
FireSp=1
ChangeSp=2

[JoyStick]
Fire=0
FireSp=1
ChangeSp=2
MegaFire=3

[Video]
fullscreen=1
aspect_ratio_correct=1
txt_fullscreen=0
